name: CD - Build, Push & Deploy

on:
  push:
    branches: [ "main" ]   # אפשר לשנות ל-branch אחר אם תרצה

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/demo_repo_mor:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/demo_repo_mor:${{ github.sha }} 
          platforms: linux/arm64
          # למשל: galgdev/devops-cd-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:  #תוספת חדשה
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} #תוספת חדשה
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} #תוספת חדשה
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN
          # script: |
          #   set -e
          #   cd /home/ubuntu/Devops_year_3/docker_compose_test
          #   # Login to DockerHub (required for PRIVATE repos)
          #   echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          #   echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" > .env
          #   echo "IMAGE_TAG=${{ github.sha }}" >> .env
          #   docker compose pull
          #   docker compose up -d --force-recreate
          script: |
            set -e
            cd /home/ubuntu/Devops_year_3/docker_compose_test
            
            # 1. מחיקת התיקייה המקולקלת שנוצרה בטעות
            sudo rm -rf nginx.conf
            
            # 2. יצירת קובץ nginx.conf תקין מאפס (בכל ריצה)
            cat <<EOF > nginx.conf
            server {
                listen 80;
                server_name mor-devops.duckdns.org;

                location / {
                    proxy_pass http://web:3002;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_cache_bypass \$http_upgrade;
                }
            }
            EOF

            # 3. פתיחת פורטים בלינוקס
            sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT || true
            sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT || true
            
            # 4. עצירת שירותי מערכת
            sudo systemctl stop nginx || true
            
            # 5. ריענון דוקר
            docker compose down || true
            
            # 6. Login & Update Env
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            echo "DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" > .env
            echo "IMAGE_TAG=${{ github.sha }}" >> .env
            
            # 7. הרצה
            docker compose pull
            docker compose up -d --force-recreate
        #
        #   docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demo_repo_mor

        #   docker compose down
        #   docker compose up -d